version: 2.0
jobs:
  test_feature:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: My fist test
          command: | 
            gradle test
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: My fist package
          command: | 
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  two_job_flow:
    jobs:
      - test_feature
      - package:
          requires:
            - test_feature
        
         
