workflows:
  version: 2.0
  two_job_flow:
  jobs:
    test:
      build: 
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
          - checkout
        - run:
            name: Test
            command: gradle test
        - store_test_results:
            path: build/test-results
    package:
      build: 
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
          - checkout
        - run:
            name: My fist package
            command: gradle jar
        - store_artifacts:
            path: build/libs
            destination: prefix