version: 2.0
jobs:
  test_feature:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: My fist test
          command: | 
            gradle test
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: My fist package
          command: | 
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
      - persist_to_workspace:
          root: .
          paths:
            - .
  dockerize:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .
      - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1
workflows:
  version: 2
  two_job_flow:
    jobs:
      - test_feature
      - package:
          requires:
            - test_feature
      - dockerize: 
          requires:
            - test_feature  